### ISSUE TITLE
Roughness and metalness Values not included in ao_met_rough map

### ISSUE THREAD

**Issue by LaurenPozzi** [facebookincubator/FBX2glTF#170] opened 2019-03-26 19:58 UTC
I have set up two Stingray materials in maya with a color map, ao map, and roughness and metalness values. When I run the converter, the materials aren't correct. For one material, I have a metalness setting of 1 and roughness of .27, the gltf has a value of 1 for both, but it looks like the ao_met_rough map that is generated is setting the roughness to 1. The other material uses .4 for metalness and .3 for roughness, and the map is setting both roughness and metalness to 1.

Attached fbx and screencaps.

[fbx2gltf help.zip](https://github.com/facebookincubator/FBX2glTF/files/3010070/fbx2gltf.help.zip)

**Comment by LaurenPozzi** [comment] 2019-03-26 23:24
After messing with this further, I realized the converter only works with metalness and roughness if you have external maps, rather than values plugged in. Might be something to look at supporting in the future?

**Comment by zellski** [comment] 2019-03-27 17:06
Thanks for spotting this! I'm going to guess https://github.com/facebookincubator/FBX2glTF/pull/171 is related to this issue?

**Comment by LaurenPozzi** [comment] 2019-03-27 17:07
Yep! We were working on it together. Thanks!

**Comment by zellski** [comment] 2019-03-30 03:07
OK, one more fix-up commit here: https://github.com/facebookincubator/FBX2glTF/commit/1f21a50cc92693b159ec3ff2c87c4c9228555e49

I'll try to get some time this weekend to put together experimental FBX files to verify that things are working as intended, but if you feels like having a go with one of your models, I am a little more confident now that things are as they should.

**Comment by zellski** [comment] 2019-04-03 17:53
@LaurenPozzi, @mtostenson –– does this look correct?

https://gltf.insimo.com/vIPZfD3fXuvSf6--39Xr8Mgvy9dlXiuozcNeN0A.Bzwovl4XrjIjqj2dtwd_MNh1md7J2qDbFFY_GA

[1058811.zip](https://github.com/facebookincubator/FBX2glTF/files/3040068/1058811.zip)


```
  "materials": [
    {
      "name": "mat_chrome",
      "alphaMode": "OPAQUE",
      "extras": {
        "fromFBX": {
          "shadingModel": "Metallic/Roughness",
          "isTruePBR": true
        }
      },
      "occlusionTexture": {
        "index": 0,
        "texCoord": 0
      },
      "pbrMetallicRoughness": {
        "baseColorFactor": [
          0.360700011253357,
          0.403899997472763,
          0.411700010299683,
          1
        ],
        "metallicFactor": 1,
        "roughnessFactor": 0.150000005960464
      }
    },
    {
      "name": "mat_seat1",
      "alphaMode": "OPAQUE",
      "extras": {
        "fromFBX": {
          "shadingModel": "Metallic/Roughness",
          "isTruePBR": true
        }
      },
      "occlusionTexture": {
        "index": 1,
        "texCoord": 0
      },
      "pbrMetallicRoughness": {
        "baseColorFactor": [
          0.850899994373322,
          0.850899994373322,
          0.850899994373322,
          1
        ],
        "metallicFactor": 0.200000002980232,
        "roughnessFactor": 0.349999994039536
      }
    },
    {
      "name": "mat_toilet",
      "alphaMode": "OPAQUE",
      "extras": {
        "fromFBX": {
          "shadingModel": "Metallic/Roughness",
          "isTruePBR": true
        }
      },
      "occlusionTexture": {
        "index": 2,
        "texCoord": 0
      },
      "pbrMetallicRoughness": {
        "baseColorFactor": [
          0.850899994373322,
          0.850899994373322,
          0.850899994373322,
          1
        ],
        "metallicFactor": 0.200000002980232,
        "roughnessFactor": 0.300000011920929
      }
    }
  ],
```

**Comment by zellski** [comment] 2019-04-03 19:00
Heh, I only now noticed that you did supply such a FBX in the original issue post! Sorry.

Out of curiosity –– are either of these models public enough that they could be committed to the repo as part of the regression suite?

**Comment by LaurenPozzi** [comment] 2019-04-04 15:43
The first one I sent cannot be used, but you can commit the second one (toilet).

**Comment by zellski** [comment] 2019-05-13 03:37
Fixed.

**Closed by zellski** 2019-05-13 03:37 UTC
Labels: bug
