### ISSUE TITLE
Embedded textures lost during conversion

### ISSUE THREAD

**Issue by ANTONBORODA** [facebookincubator/FBX2glTF#152] opened 2018-12-26 14:19 UTC
Hello,
When trying to convert the attached file from FBX to glTF all the textures, except one, are lost and all texture references in glTF are replaced with the first one. It's working fine with 3DS Max and Unity.
Tried to convert on Windows and Mac OS. Same result.
[testRoom_asci.FBX.zip](https://github.com/facebookincubator/FBX2glTF/files/2710362/testRoom_asci.FBX.zip)

**Comment by zellski** [comment] 2018-12-26 21:03
Thank you very much, especially for including a FBX file to reproduce it! I'll dig into this today. I'm especially interested (and humbled) because I've seen the behaviour you describe once before, but at the time I dismissed it as a problem with the FBX...

**Comment by ANTONBORODA** [comment] 2019-01-14 07:20
Any news on this issue?

**Comment by ANTONBORODA** [comment] 2019-01-14 15:01
I digged a little deeper and it seems like a problem with an FBX file and not the converter.

**Comment by ANTONBORODA** [comment] 2019-01-22 09:50
I've removed a previous large repro project.
Here's a very simple one. Only 2 textures and second one is lost during conversion.
[simpleRepro.fbx.zip](https://github.com/facebookincubator/FBX2glTF/files/2782187/simpleRepro.fbx.zip)

**Comment by zellski** [comment] 2019-01-22 16:22
Great, thanks. Should be able to investigate shortly.

**Comment by zellski** [comment] 2019-01-25 00:15
Ugh. We were using the logical FBX name of the texture as a key, and both yours are named "Diffuse Texture". I'll figure out what's a better discriminator –– probably file location –– and fix it.

**Comment by zellski** [comment] 2019-01-25 01:04
Fixed in https://github.com/facebookincubator/FBX2glTF/commit/12025de1799ef8d743e2543823cacdac185bdbdf. Will be included in 0.9.6.

**Closed by zellski** 2019-01-25 01:04 UTC
