### ISSUE TITLE
GLTF Model is partially rendered with missing elements

### ISSUE THREAD

**Issue by Pratyush1184** [facebookincubator/FBX2glTF#164] opened 2019-02-25 13:53 UTC
I am using a Ubuntu 18.04.2 LTS(64-bit) on my machine with 16 GB of RAM.
On executing the executable directly, the process failed.
So, I looked into the source code of "FindFBX.cmake" file and changed the path in line number 72 and 73 to:
    set(_fbxsdk_libdir_debug "lib/gcc4/x64/debug")
    set(_fbxsdk_libdir_release "lib/gcc4/x64/release")
Then I compiled the code with cmake using the command given in the README file:
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
On getting a dependency error due to libxml2, I installed the package libxml2-dev using the command:
sudo apt-get install libxml2-dev
The compilation was successful and then I run the following command:
make -Cbuild -j4 install
I obtained an executable file named FBX2glTF-linux-x64.
When I used this executable file to test with a few sample FBX model that I uploaded(HP_Model), I obtained the corresponding GLTF files:
On viewing the GLTF models on Babylon sandbox(https://sandbox.babylonjs.com/), the models appeared partially and incomplete with missing entities. I am attaching the screenshots for the rendered model and also the corresponding FBX models with their rendered view:

[HP_Model.zip](https://github.com/facebookincubator/FBX2glTF/files/2900783/HP_Model.zip)
![fbx_rendering_hp_model](https://user-images.githubusercontent.com/20305094/53341749-68264f80-3932-11e9-8fe5-2215e0fb911d.png)
![gltf_rendering_hp_model1](https://user-images.githubusercontent.com/20305094/53341750-68264f80-3932-11e9-999f-4347f5385310.png)
![gltf_rendering_hp_model2](https://user-images.githubusercontent.com/20305094/53341751-68264f80-3932-11e9-95d8-18a62cca2f08.png)

Please look into the issue. Thanks a lot.

**Comment by zellski** [comment] 2019-02-25 17:43
Thanks for the report! I am curious, could you tell me what "On executing the executable directly, the process failed." means? Do you have a screenshot or a copy & paste? Note that the current release is very old and quite a few bugs have been fixed since. You can also try binaries [here](https://dev.azure.com/parwinzell/FBX2glTF/) (I just added this link to the README as well.)

Thanks also for the reminder that with the most recent FBX SDK, packages such as `libxml2-dev` may be needed on the system. I should verify the precise requirements and update the documentation.

As for the final glTF bug, I will try out HP_Model.zip later today and see if I can reproduce it and/or figure out what's going on.

**Comment by zellski** [comment] 2019-02-25 18:57
I've looked into HP_Model.FBX some. The FBX SDK seems to crash just trying to triangulate it. When I look at the file in Autodesk's own FBX viewer, it's clearly missing geometry. So I'm going to propose that the FBX model itself contains a lot of broken geometry. This is not uncommon with CAD type models, it seems to me. What's the source format, do you know? Perhaps whatever program you used to construct the FBX has a bad exporter?

**Comment by Pratyush1184** [comment] 2019-02-26 09:56
The FBX model was exported from 3ds max. The FBX model seems fine to me as I have **already posted a screenshot of the model above when viewed with Autodesk's own FBX viewer**.
![fbx_rendering_hp_model](https://user-images.githubusercontent.com/20305094/53404056-dde5f600-39da-11e9-8492-1f9f8fee352c.png)

**Comment by Pratyush1184** [comment] 2019-02-26 10:11
> Thanks for the report! I am curious, could you tell me what "On executing the executable directly, the process failed." means? Do you have a screenshot or a copy & paste? Note that the current release is very old and quite a few bugs have been fixed since. You can also try binaries [here](https://dev.azure.com/parwinzell/FBX2glTF/) (I just added this link to the README as well.)
> 
> Thanks also for the reminder that with the most recent FBX SDK, packages such as `libxml2-dev` may be needed on the system. I should verify the precise requirements and update the documentation.
> 
> As for the final glTF bug, I will try out HP_Model.zip later today and see if I can reproduce it and/or figure out what's going on.

After installing the npm package and running the node server, the process failed with an error. The package libxml2-dev was already installed by me using the command:
sudo apt-get install libxml2-dev
As I previously mentioned I changed the paths in the cmake file as the code didn't compile successfully until then. On traversing the file path I found the actual installation library path and hence made some changes in the code. After changing the paths, the code compiled successfully and the executable was generated successfully.

**Comment by zellski** [comment] 2019-02-26 18:21
I see, the online viewer. You're right, it renders correctly there, after whatever server-side processing takes place. The crash we see is essentially a bug in the FBX SDK. It's out of my control to fix. I have at times thought of writing my own triangulation code to replace what we use in the SDK, but that's quite a massive endeavour, given that this is a volunteer project. If you have any urge to undertake it, diffs are always welcome! :)

As for your compilation error, I don't understand why you would need to change paths back to 'gcc4'. That was how previous versions of the FBX SDK worked. With 2019.2, the paths changed to just 'gcc'.

**Comment by Pratyush1184** [comment] 2019-02-27 10:58
Don't really know but I didn't have a gcc in the described path and had a gcc4 folder instead. So I tried changing the folder path and it worked.

**Comment by zellski** [comment] 2019-02-27 19:13
Except it kind of didn't, right? What I'm getting at is, it sounds likely some of these follow-up problems are due to your original tweaks. You are likely linking to the wrong FBX SDK libraries? I don't know.

I'm tentatively closing this, because I don't have the cycles to work around the FBX SDK's bugs. I'm going to guess your FBX has some questionable geometry in it, and that Autodesk's online viewer just uses some forgiving server process to convert it to whatever format they deliver to the browser. Don't get me wrong, it would be much better if we **did** handle this correctly. But ultimately I have to punt responsibility to Autodesk.

**Closed by zellski** 2019-02-27 19:13 UTC
Labels: bug
