### ISSUE TITLE
Textures not included

### ISSUE THREAD

**Issue by FreakTheMighty** [facebookincubator/FBX2glTF#54] opened 2017-12-06 22:28 UTC
I'm having issues converting an FBX with textures. Given this model: https://free3d.com/3d-model/batman70-68300.html

```
FBX2glTF --input ./BAC_Batman70s_rocksteady/batman70.fbx  --output /tmp/Batman
```

The output is 
```
Warning: could not find a local image file for texture: file4.
Original filename: /Users/jvanderdoes/Downloads/BAC_Batman70s_rocksteady/Batman_V3_Cape_DS_1-4_D.tga
Warning: could not find a local image file for texture: file3.
Original filename: /Users/jvanderdoes/Downloads/BAC_Batman70s_rocksteady/Batman_V3_Cape_DS_1-4_D.tga
Warning: could not find a local image file for texture: file1.
Original filename: /Users/jvanderdoes/Downloads/BAC_Batman70s_rocksteady/DLC3_Batman1970_head_D.tga
Warning: could not find a local image file for texture: file2.
Original filename: /Users/jvanderdoes/Downloads/BAC_Batman70s_rocksteady/DLC3_Batman1970_leg_D.tga
Warning: could not find a local image file for texture: file5.
Original filename: /Users/jvanderdoes/Downloads/BAC_Batman70s_rocksteady/DLC3_Batman1970_torso_D.tga
Warning: Mat [Cape2]: Can't handle texture for TransparentColor; discarding.
Warning: Mat [Cape1]: Can't handle texture for TransparentColor; discarding.
Warning: animation 'Take 001' has zero channels. Skipping.
Wrote 12853 bytes of glTF to /tmp/Batman_out/Batman.gltf.
Wrote 395644 bytes of binary data to /tmp/Batman_out/buffer.bin.
```
What's confusing is that those are valid file paths, so I'm not sure why it is having issues finding the textures.

**Comment by FreakTheMighty** [comment] 2017-12-06 22:50
Here is the resulting gltf https://gist.github.com/FreakTheMighty/5193c2c81c682ebb730bb7e805263577

**Comment by zellski** [comment] 2017-12-07 03:14
@FreakTheMighty -- the issue is that glTF simply doesn't allow the .tga file format. In fact, the only image files formally accepted are PNG and JPG! Luckily, if you convert the images and put the new ones in the same place, with exactly the same name except for the file extension, the converter *should* pick the new ones up, even with the suffix changed. This is by design, so you can recover from precisely this situation (that said, I'm not sure anybody's tested this particular feature in many moons, so if it still doesn't work, let me know). 

Obviously if you have transparency in the textures you will need to use PNG for those. 

The converter should probably warn on bad filetypes, huh. Yeah. I'll file an issue for that. :)

**Comment by FreakTheMighty** [comment] 2017-12-07 03:26
Ah cool, I'll give that a try and report back tomorrow.

**Comment by FreakTheMighty** [comment] 2017-12-07 03:53
I can confirm that the converted pngs were recognized (neat trick), however now I've bumped into that related #55 issue. The pngs show up in the `out` directory white.

**Comment by zellski** [comment] 2017-12-07 05:20
Glad that part worked, at least! I'll close this issue out and we'll continue tracking the remaining problem(s) in https://github.com/facebookincubator/FBX2glTF/issues/55.

**Closed by zellski** 2017-12-07 05:20 UTC
