### ISSUE TITLE
I turned fbx, turned on Draco compression and crash

### ISSUE THREAD

**Issue by gameatp** [facebookincubator/FBX2glTF#166] opened 2019-03-08 12:45 UTC
Here is the FBX source file

[testmodel.zip](https://github.com/facebookincubator/FBX2glTF/files/2945831/testmodel.zip)

**Comment by zellski** [comment] 2019-05-14 14:33
Hi... can't reproduce this. Can you please tell me which version of the tool you used (the 0.9.5 release, or a recent build, or did you build it yourself?) and ideally what the command looked like?

**Comment by gameatp** [comment] 2019-05-15 02:24
> Hi... can't reproduce this. Can you please tell me which version of the tool you used (the 0.9.5 release, or a recent build, or did you build it yourself?) and ideally what the command looked like?

I compiled a version myself, as if the weight problem led to dividing by 0, and I solved it myself.

**Comment by zellski** [comment] 2019-05-15 04:38
Oh right! OK, closing this then.

**Closed by zellski** 2019-05-15 04:38 UTC
