### ISSUE TITLE
Textures not converting using node version

### ISSUE THREAD

**Issue by CosmoKnot98** [facebookincubator/FBX2glTF#89] opened 2018-03-24 19:43 UTC
I have been trying to convert an FBX to a GLTF using the Node/JS version.  The GLTF comes out fine except the textures are missing.  In the "images" array, we are getting blank images with the following URI:

data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=

Also, important to note that we are getting no console errors.

**Comment by zellski** [comment] 2018-03-24 19:48
Hi @CosmoKnot98 -- if you re-run the conversion with the verbose (-v) flag, what's the output?

The converter uses this blank GIF when it can't locate the file corresponding to the texture. I assume your texture files are separate from the .fbx? It matters where they're located and (exactly) what they're named. The --verbose output should help there.

The easiest way to be sure the textures resolve correctly is to export the FBX with embedded resources, meaning the textures are part of the FBX, and FBX2glTF auto-extracts them, so it knows exactly where to find them.

**Comment by zellski** [comment] 2018-03-24 20:43
I see. I think the problem is that you only get the verbose output if there's an error during conversion. That's pretty stupid on my part. I'll see if I can fix that,.

Meanwhile, what happens if you explicitly run the binary converter on the command line, rather than rely on the node.js API? If you're not comfortable doing that, would you be able to share the FBX in question?

**Comment by CosmoKnot98** [comment] 2018-03-24 21:20
Okay, this is the test model (FBX) that we have been working with that won't render textures in a converted GLTF using the Node.JS version but will render textures in Unity.  I have attached both the FBX and the GLTF that it converts to below.

[Test_Wolf.zip](https://github.com/facebookincubator/FBX2glTF/files/1844804/Test_Wolf.zip)

[wolf_output.zip](https://github.com/facebookincubator/FBX2glTF/files/1844807/wolf_output.zip)

**Comment by zellski** [comment] 2018-03-25 22:43
Hey @CosmoKnot98 -- this is actually a bug in FBX2glTF. It first finds the correct texture locations, then loses them all by trying to be too clever and failing.

I'll fix that. Meanwhile a super-easy workaround is to just move the textures out of the 'textures' subdirectory, placing them next to the .fbx in the directory structure.

I'm attaching the resulting .glb.

[Wolf_One_fbx7.4_binary.glb.zip](https://github.com/facebookincubator/FBX2glTF/files/1845905/Wolf_One_fbx7.4_binary.glb.zip)

**Comment by zellski** [comment] 2018-03-28 03:03
The texture resolution bug is fixed in https://github.com/facebookincubator/FBX2glTF/commit/3f1590a26b91de7181fbb2ec279afa930eb64d8a, and will be available in release 0.9.5 shortly.

**Closed by zellski** 2018-03-28 03:03 UTC
Labels: bug
